# Generated by Django 6.0.2 on 2026-03-01 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='specializations/media/')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='specializations/media/')),
                ('hero_title', models.CharField(blank=True, max_length=255)),
                ('hero_description', models.TextField(blank=True)),
                ('hero_banner', models.ImageField(blank=True, null=True, upload_to='specializations/media/')),
                ('main_title', models.CharField(blank=True, max_length=255)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='specializations/media/')),
                ('main_description', models.TextField(blank=True)),
                ('secondary_title', models.CharField(blank=True, max_length=255)),
                ('secondary_image', models.ImageField(blank=True, null=True, upload_to='specializations/media/')),
                ('long_description_primary', models.TextField(blank=True)),
                ('long_description_secondary', models.TextField(blank=True)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('primary_keywords', models.CharField(blank=True, max_length=255)),
                ('secondary_keywords', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('canonical_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='administrator.branch')),
            ],
            options={
                'verbose_name': 'Specialization',
                'verbose_name_plural': 'Specializations',
                'ordering': ['-created_at'],
            },
        ),
    ]
