# Generated by Django 6.0.2 on 2026-03-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='featured_image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='specialization',
            name='hero_banner_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='specialization',
            name='main_image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='specialization',
            name='secondary_image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/specializations/'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='hero_banner',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/specializations/'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/specializations/'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/specializations/'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='secondary_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/specializations/'),
        ),
    ]
