# Generated by Django 6.0.2 on 2026-03-06 14:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_specialization_featured_image_alt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='long_description_primary',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='long_description_secondary',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
