# Generated by Django 6.0.2 on 2026-03-06 15:23

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_alter_specialization_long_description_primary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='long_description_primary',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='long_description_secondary',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
