# Generated by Django 6.0.2 on 2026-03-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_alter_specialization_long_description_primary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='og_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='specialization',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo/og/'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='og_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
