# Generated by Django 6.0.2 on 2026-03-07 11:36

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_redirect'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('canonical_url', models.URLField(blank=True)),
                ('primary_keywords', models.CharField(blank=True, max_length=255)),
                ('secondary_keywords', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('og_title', models.CharField(blank=True, max_length=255)),
                ('og_description', models.TextField(blank=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/og/')),
                ('doctor_hero_banner', models.ImageField(blank=True, null=True, upload_to='uploads/doctors/')),
                ('doctor_hero_banner_alt', models.CharField(blank=True, max_length=255)),
                ('designation', models.CharField(blank=True, max_length=200)),
                ('years_of_experience', models.PositiveIntegerField(help_text='Years of experience')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='uploads/doctors/profile/')),
                ('profile_image_alt', models.CharField(blank=True, max_length=255)),
                ('specialized_in', models.CharField(blank=True, help_text='Example: Heart Surgery, Angioplasty', max_length=255)),
                ('languages', models.CharField(blank=True, help_text='Example: English, Hindi, Malayalam', max_length=255)),
                ('procedures', models.TextField(blank=True, help_text='Major procedures performed')),
                ('success_rate', models.TextField(blank=True, null=True)),
                ('patients_treated', models.TextField(blank=True, help_text='Total patients treated', null=True)),
                ('short_bio', models.TextField(blank=True)),
                ('full_bio', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='administrator.branch')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='administrator.specialization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name'],
            },
        ),
    ]
