# Generated by Django 6.0.2 on 2026-03-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirect',
            name='model_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
