# Generated by Django 6.0.2 on 2026-03-15 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0010_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
