# Generated by Django 6.0.2 on 2026-03-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_delete_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('canonical_url', models.URLField(blank=True)),
                ('primary_keywords', models.CharField(blank=True, max_length=255)),
                ('secondary_keywords', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('og_title', models.CharField(blank=True, max_length=255)),
                ('og_description', models.TextField(blank=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/og/')),
                ('banner_title', models.CharField(max_length=255)),
                ('banner_description', models.TextField(blank=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='listing/banner/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
