# Generated by Django 6.0.2 on 2026-03-15 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0012_listingpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListingPage',
        ),
    ]
