# Generated by Django 6.0.2 on 2026-03-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0014_listingpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingpage',
            name='page_cta',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='listingpage',
            name='page_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='listingpage',
            name='page_title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
