# Generated by Django 6.0.2 on 2026-03-15 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0016_contentcategory_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('canonical_url', models.URLField(blank=True)),
                ('primary_keywords', models.CharField(blank=True, max_length=255)),
                ('secondary_keywords', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('og_title', models.CharField(blank=True, max_length=255)),
                ('og_description', models.TextField(blank=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/og/')),
                ('content_type', models.CharField(choices=[('blog', 'Blog'), ('article', 'Article'), ('news', 'News'), ('health_package', 'Health Package'), ('insurance', 'Insurance')], default='blog', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField(blank=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='content/featured/')),
                ('content', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='administrator.contentcategory')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_contents', to='administrator.doctor')),
                ('tags', models.ManyToManyField(blank=True, related_name='contents', to='administrator.tag')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
