# Generated by Django 6.0.2 on 2026-03-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0020_doctoreducation'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoreducation',
            name='specialization_in',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
