# Generated by Django 6.0.2 on 2026-03-20 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0022_doctorcertification_doctorexpertise_doctormembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecializationFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='administrator.specialization')),
            ],
        ),
        migrations.CreateModel(
            name='SpecializationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='uploads/specializations/services/')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='administrator.specialization')),
            ],
        ),
    ]
