# Generated by Django 6.0.2 on 2026-03-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0023_specializationfaq_specializationservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(help_text='Example: Doctor, Manager, Staff', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/team/')),
                ('short_description', models.TextField(blank=True, help_text='Short bio or introduction')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(blank=True, help_text='Example: Patient, CEO, Business Owner', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/testimonials/')),
                ('short_description', models.TextField(help_text='Customer feedback / testimonial text')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
