# Generated by Django 6.0.2 on 2026-03-21 13:17

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0024_teammember_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', ckeditor_uploader.fields.RichTextUploadingField()),
                ('phone_primary', models.CharField(help_text='Main contact number', max_length=20)),
                ('phone_secondary', models.CharField(blank=True, help_text='Optional secondary number', max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, help_text='WhatsApp number', max_length=20)),
                ('email_primary', models.EmailField(max_length=254)),
                ('email_secondary', models.EmailField(blank=True, max_length=254)),
                ('map_embed', models.TextField(blank=True, help_text='Paste Google Maps iframe embed code')),
                ('emergency_info', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
