# Generated by Django 6.0.2 on 2026-03-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0025_contactpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingpage',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/listing_banner/'),
        ),
    ]
