# Generated by Django 6.0.2 on 2026-03-22 14:18

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0026_alter_listingpage_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='main_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
