# Generated by Django 6.0.2 on 2026-03-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0027_alter_specialization_main_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='hero_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hero_title',
            field=models.TextField(blank=True, help_text='hero title'),
        ),
    ]
