# Generated by Django 6.0.2 on 2026-03-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0028_doctor_hero_description_doctor_hero_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='hero_banner',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/contents/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='hero_description',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='hero_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
