# Generated by Django 6.0.2 on 2026-03-26 09:28

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0029_content_hero_banner_alter_doctor_hero_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('canonical_url', models.URLField(blank=True)),
                ('primary_keywords', models.CharField(blank=True, max_length=255)),
                ('secondary_keywords', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('og_title', models.CharField(blank=True, max_length=255)),
                ('og_description', models.TextField(blank=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/og/')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='uploads/services/')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='uploads/services/')),
                ('featured_image_alt', models.CharField(blank=True, max_length=255)),
                ('hero_title', models.CharField(blank=True, max_length=255)),
                ('hero_description', models.TextField(blank=True)),
                ('hero_banner', models.ImageField(blank=True, null=True, upload_to='uploads/services/')),
                ('hero_banner_alt', models.CharField(blank=True, max_length=255)),
                ('main_title', models.CharField(blank=True, max_length=255)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='uploads/services/')),
                ('main_image_alt', models.CharField(blank=True, max_length=255)),
                ('main_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('long_description_primary', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('long_description_secondary', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_services', to='administrator.specialization')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-created_at'],
            },
        ),
    ]
