# Generated by Django 6.0.2 on 2026-03-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0032_packagecategory_packagecategoryfaq_packageproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageproduct',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/packages/'),
        ),
        migrations.AddField(
            model_name='packageproduct',
            name='featured_image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
