# Generated by Django 6.0.2 on 2026-03-27 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0033_packageproduct_featured_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagecategory',
            name='Specialization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='package_category', to='administrator.specialization'),
            preserve_default=False,
        ),
    ]
