# Generated by Django 6.0.2 on 2026-03-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0034_packagecategory_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagecategory',
            name='short_description',
            field=models.TextField(blank=True),
        ),
    ]
