# Generated by Django 6.0.2 on 2026-03-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0035_packagecategory_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.TextField(blank=True, help_text='Optional short summary')),
                ('long_description', models.TextField(blank=True, help_text='Optional detailed description')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='uploads/insurance/')),
                ('featured_image_alt', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Insurance',
                'verbose_name_plural': 'Insurance',
                'ordering': ['-created_at'],
            },
        ),
    ]
