# Generated by Django 6.0.2 on 2026-03-27 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0037_legalpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='uploads/settings/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='uploads/settings/')),
                ('footer_logo', models.ImageField(blank=True, null=True, upload_to='uploads/settings/')),
                ('address', models.TextField(blank=True)),
                ('phone_primary', models.CharField(blank=True, max_length=50)),
                ('phone_secondary', models.CharField(blank=True, max_length=50)),
                ('email_primary', models.EmailField(blank=True, max_length=254)),
                ('email_secondary', models.EmailField(blank=True, max_length=254)),
                ('whatsapp_number', models.CharField(blank=True, max_length=50)),
                ('whatsapp_message', models.CharField(blank=True, max_length=255)),
                ('is_whatsapp_enabled', models.BooleanField(default=True)),
                ('footer_description', models.TextField(blank=True)),
                ('copyright_text', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('whatsapp', 'WhatsApp'), ('other', 'Other')], max_length=50)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(blank=True, help_text='Example: fab fa-facebook-f', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(help_text='Example: /about/ or /contact/', max_length=255)),
                ('icon_class', models.CharField(blank=True, help_text='Optional icon (ex: fas fa-home)', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='administrator.menugroup')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
