# Generated by Django 6.0.2 on 2026-03-28 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0038_globalsettings_menugroup_sociallink_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='administrator.menuitem'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='icon_class',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
