# Generated by Django 6.0.2 on 2026-03-28 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0039_menuitem_parent_alter_menuitem_icon_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('canonical_url', models.URLField(blank=True)),
                ('primary_keywords', models.CharField(blank=True, max_length=255)),
                ('secondary_keywords', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('og_title', models.CharField(blank=True, max_length=255)),
                ('og_description', models.TextField(blank=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/og/')),
                ('title', models.CharField(max_length=255)),
                ('about_subtitle', models.CharField(blank=True, max_length=255)),
                ('about_title', models.CharField(blank=True, max_length=255)),
                ('about_description', models.TextField(blank=True)),
                ('about_image1', models.ImageField(blank=True, upload_to='home/about/')),
                ('about_image1_alt', models.CharField(blank=True, max_length=255)),
                ('about_image2', models.ImageField(blank=True, upload_to='home/about/')),
                ('about_image2_alt', models.CharField(blank=True, max_length=255)),
                ('about_image3', models.ImageField(blank=True, upload_to='home/about/')),
                ('about_image3_alt', models.CharField(blank=True, max_length=255)),
                ('specialization_subtitle', models.CharField(blank=True, max_length=255)),
                ('specialization_title', models.CharField(blank=True, max_length=255)),
                ('specialization_description', models.TextField(blank=True)),
                ('staff_title', models.CharField(blank=True, max_length=255)),
                ('staff_subtitle', models.CharField(blank=True, max_length=255)),
                ('staff_description', models.TextField(blank=True)),
                ('why_choose_title', models.CharField(blank=True, max_length=255)),
                ('why_choose_subtitle', models.CharField(blank=True, max_length=255)),
                ('why_choose_description', models.TextField(blank=True)),
                ('blog_subtitle', models.CharField(blank=True, max_length=255)),
                ('blog_title', models.CharField(blank=True, max_length=255)),
                ('blog_description', models.TextField(blank=True)),
                ('article_subtitle', models.CharField(blank=True, max_length=255)),
                ('article_title', models.CharField(blank=True, max_length=255)),
                ('article_description', models.TextField(blank=True)),
                ('faq_subtitle', models.CharField(blank=True, max_length=255)),
                ('faq_title', models.CharField(blank=True, max_length=255)),
                ('faq_description', models.TextField(blank=True)),
                ('testimonial_subtitle', models.CharField(blank=True, max_length=255)),
                ('testimonial_title', models.CharField(blank=True, max_length=255)),
                ('testimonial_description', models.TextField(blank=True)),
                ('parallax_subtitle', models.CharField(blank=True, max_length=255)),
                ('parallax_title', models.CharField(blank=True, max_length=255)),
                ('parallax_description', models.TextField(blank=True)),
                ('parallax_cta', models.CharField(blank=True, max_length=255)),
                ('parallax_banner', models.ImageField(blank=True, upload_to='home/parallax/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomeFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='home/features/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='administrator.homepage')),
            ],
        ),
        migrations.CreateModel(
            name='HomeFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='administrator.homepage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='home/banner/')),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='administrator.homepage')),
            ],
        ),
        migrations.CreateModel(
            name='WhyChooseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='e.g. fa fa-check', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_items', to='administrator.homepage')),
            ],
        ),
    ]
