# Generated by Django 6.0.2 on 2026-03-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0040_homepage_homefeature_homefaq_homebanner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home/banner/'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homefeature',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home/features/'),
        ),
        migrations.AlterField(
            model_name='homefeature',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_image1',
            field=models.ImageField(blank=True, null=True, upload_to='home/about/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_image2',
            field=models.ImageField(blank=True, null=True, upload_to='home/about/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_image3',
            field=models.ImageField(blank=True, null=True, upload_to='home/about/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='parallax_banner',
            field=models.ImageField(blank=True, null=True, upload_to='home/parallax/'),
        ),
        migrations.AlterField(
            model_name='whychooseitem',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='home/whychoose/'),
        ),
        migrations.AlterField(
            model_name='whychooseitem',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
