# Generated by Django 6.0.2 on 2026-03-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0041_alter_homebanner_description_alter_homebanner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whychooseitem',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
