# Generated by Django 6.0.2 on 2026-03-29 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0042_alter_whychooseitem_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homefaq',
            name='homepage',
        ),
        migrations.RemoveField(
            model_name='homefeature',
            name='homepage',
        ),
        migrations.RemoveField(
            model_name='whychooseitem',
            name='homepage',
        ),
        migrations.DeleteModel(
            name='HomeBanner',
        ),
        migrations.DeleteModel(
            name='HomeFAQ',
        ),
        migrations.DeleteModel(
            name='HomeFeature',
        ),
        migrations.DeleteModel(
            name='WhyChooseItem',
        ),
    ]
