# Generated by Django 6.0.2 on 2026-03-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0043_remove_homefaq_homepage_remove_homefeature_homepage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='why_choose_banner',
            field=models.ImageField(blank=True, null=True, upload_to='home/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_image1',
            field=models.ImageField(blank=True, null=True, upload_to='home/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_image2',
            field=models.ImageField(blank=True, null=True, upload_to='home/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_image3',
            field=models.ImageField(blank=True, null=True, upload_to='home/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='parallax_banner',
            field=models.ImageField(blank=True, null=True, upload_to='home/'),
        ),
    ]
