# Generated by Django 6.0.2 on 2026-03-29 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0045_alter_homepage_about_image1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/banner/')),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='administrator.homepage')),
            ],
        ),
    ]
