# Generated by Django 6.0.2 on 2026-03-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0047_alter_homebanner_image_homefeature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homefeature',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/home/features/'),
        ),
    ]
