# Generated by Django 6.0.2 on 2026-03-29 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0050_homefaq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homefaq',
            name='homepage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homefaqs', to='administrator.homepage'),
        ),
    ]
