# Generated by Django 6.0.2 on 2026-03-29 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0051_alter_homefaq_homepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeFAQ',
        ),
    ]
