# Generated by Django 6.0.2 on 2026-03-29 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0052_delete_homefaq'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homefaqs', to='administrator.homepage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
