# Generated by Django 6.0.2 on 2026-03-29 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0053_homefaq'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/home/highlights/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlight_items', to='administrator.homepage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
