# Generated by Django 6.0.2 on 2026-04-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0054_highlightitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('blog', 'Blog'), ('article', 'Article'), ('news', 'News')], default='blog', max_length=50),
        ),
    ]
