# Generated by Django 6.0.2 on 2026-04-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0058_doctorleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalpage',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
