# Generated by Django 6.0.2 on 2026-04-04 06:38

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0059_legalpage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='chairman_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='chairman_msg',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='chairman_profile',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/about/'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='section_five',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
