# Generated by Django 6.0.2 on 2026-04-04 06:51

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0060_aboutpage_chairman_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='chairman_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
