# Generated by Django 6.0.2 on 2026-04-05 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0061_alter_aboutpage_chairman_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagecategory',
            name='Specialization',
        ),
        migrations.RemoveField(
            model_name='packageproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='specializationservice',
            name='specialization',
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.TextField(blank=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='uploads/packages/')),
                ('main_image_alt', models.CharField(blank=True, max_length=255)),
                ('parameters', models.TextField(blank=True, help_text='Example: Blood test, ECG, etc.')),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_category', to='administrator.specialization')),
            ],
            options={
                'verbose_name': 'Package Category',
                'verbose_name_plural': 'Package Categories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='packagefeature',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='administrator.packages'),
        ),
        migrations.DeleteModel(
            name='PackageCategoryFAQ',
        ),
        migrations.DeleteModel(
            name='PackageCategory',
        ),
        migrations.DeleteModel(
            name='SpecializationService',
        ),
        migrations.DeleteModel(
            name='PackageProduct',
        ),
    ]
