# Generated by Django 6.0.2 on 2026-04-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0063_gallery_alter_packages_specialization_galleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='video_url',
            field=models.TextField(blank=True, help_text='Paste full YouTube embed iframe code', null=True),
        ),
    ]
