# Generated by Django 6.0.2 on 2026-04-07 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0064_alter_gallery_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorschedule',
            name='specialization',
        ),
    ]
