from django.urls import path
from .views import dashboard,BranchCreateView,BranchListView,BranchUpdateView,BranchDeleteView,SpecializationListView,SpecializationCreateView,SpecializationUpdateView,SpecializationDeleteView,DoctorCreateView,DoctorListView,DoctorUpdateView,DoctorDeleteView,load_specializations,ListingPageListView,ListingPageCreateView,ListingPageUpdateView,ListingPageDeleteView,ContentListView,ContentCreateView,ContentUpdateView,ContentDeleteView,ContentCategoryCreateView,ContentCategoryListView,ContentCategoryDeleteView,ContentCategoryUpdateView,TagCreateView,TagListView,TagUpdateView,TagDeleteView,about_manage,TestimonialCreateView,TestimonialListView,TestimonialUpdateView,TestimonialDeleteView,TeamCreateView,TeamUpdateView,TeamDeleteView,TeamListView,contact_manage,ContactSubmissionListView,ContactSubmissionDeleteView,mark_submission_read,ServiceCreateView,ServiceListView,ServiceUpdateView,ServiceDeleteView,PackageCreateView,PackageDeleteView,PackageListView,PackageUpdateView,InsuranceCreateView,InsuranceListView,InsuranceDeleteView,InsuranceUpdateView,LegalPageCreateView,LegalPageDeleteView,LegalPageUpdateView,LegalPageListView,global_settings_manage,SocialLinkCreateView,SocialLinkListView,SocialLinkUpdateView,SocialLinkDeleteView,MenuGroupListView,MenuGroupCreateView,MenuGroupUpdateView,MenuGroupDeleteView,homepage_manage,DoctorScheduleCreateView,load_doctors_by_specialization,DoctorScheduleListView,DoctorScheduleUpdateView,DoctorScheduleDeleteView,DoctorLeaveCreateView,DoctorLeaveDeleteView,DoctorLeaveListView,DoctorLeaveUpdateView,booking_list,update_booking_status,delete_booking,GalleryCreateView,GalleryListView,GalleryUpdateView,GalleryDeleteView,gallery_image_delete




app_name= 'administrator'

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('homepage/', homepage_manage, name='homepage-manage'),
    path('about/manage/',about_manage, name='about-manage'),
    path('branches/', BranchListView.as_view(), name='branch-list'),
    path('branches/create/', BranchCreateView.as_view(), name='branch-create'),
    path('branches/<int:pk>/update/', BranchUpdateView.as_view(), name='branch-update'),
    path('branches/<int:pk>/delete/', BranchDeleteView.as_view(), name='branch-delete'),
    path('specializations/', SpecializationListView.as_view(), name='specialization-list'),
    path('specializations/create/', SpecializationCreateView.as_view(), name='specialization-create'),
    path('specializations/<int:pk>/update/',SpecializationUpdateView.as_view(),name='specialization-update'),
    path('specializations/<int:pk>/delete/',SpecializationDeleteView.as_view(),name='specialization-delete'),
    path('services/', ServiceListView.as_view(), name='service-list'),
    path('services/add/', ServiceCreateView.as_view(), name='service-create'),
    path('services/edit/<int:pk>/', ServiceUpdateView.as_view(), name='service-update'),
    path('services/delete/<int:pk>/', ServiceDeleteView.as_view(), name='service-delete'),
    path( 'doctors/',DoctorListView.as_view(),name="doctor-list"),
    path('doctors/create/',DoctorCreateView.as_view(),name="doctor_create"),
    path('doctors/<int:pk>/update/',DoctorUpdateView.as_view(),name="doctor-update"),
    path('doctors/<int:pk>/delete/',DoctorDeleteView.as_view(),name="doctor-delete"),
    path('ajax/load-specializations/',load_specializations,name="load_specializations"),
    path( 'listing-pages/',ListingPageListView.as_view(),name="listing-page-list"),
    path("listing-pages/create/",ListingPageCreateView.as_view(),name="listing-page-create"),
    path("listing-pages/<int:pk>/update/",ListingPageUpdateView.as_view(),name="listing-page-update"),
    path("listing-pages/<int:pk>/delete/",ListingPageDeleteView.as_view(),name="listing-page-delete"),
    path("contents/",ContentListView.as_view(),name="content-list"),
    path("contents/create/",ContentCreateView.as_view(),name="content-create"),
    path("contents/<int:pk>/update/",ContentUpdateView.as_view(),name="content-update"),
    path("contents/<int:pk>/delete/",ContentDeleteView.as_view(),name="content-delete"),
    path("content-categories/",ContentCategoryListView.as_view(),name="content-category-list"),
    path("content-categories/create/",ContentCategoryCreateView.as_view(),name="content-category-create"),
    path("content-categories/<int:pk>/update/",ContentCategoryUpdateView.as_view(),name="content-category-update"),
    path("content-categories/<int:pk>/delete/",ContentCategoryDeleteView.as_view(),name="content-category-delete"),
    path("tags/",TagListView.as_view(),name="tag-list"),
    path("tags/create/",TagCreateView.as_view(),name="tag-create"),
    path("tags/<int:pk>/update/",TagUpdateView.as_view(),name="tag-update"),
    path("tags/<int:pk>/delete/",TagDeleteView.as_view(),name="tag-delete"),
    path('testimonial/', TestimonialListView.as_view(), name='testimonial-list'),
    path('testimonial/add/', TestimonialCreateView.as_view(), name='testimonial-create'),
    path('testimonial/edit/<int:pk>/', TestimonialUpdateView.as_view(), name='testimonial-update'),
    path('testimonial/delete/<int:pk>/', TestimonialDeleteView.as_view(), name='testimonial-delete'),
    path('team/', TeamListView.as_view(), name='team-list'),
    path('team/add/', TeamCreateView.as_view(), name='team-create'),
    path('team/edit/<int:pk>/', TeamUpdateView.as_view(), name='team-update'),
    path('team/delete/<int:pk>/', TeamDeleteView.as_view(), name='team-delete'),
    path('contact/manage/', contact_manage, name='contact-manage'),
    path('contact/submissions/', ContactSubmissionListView.as_view(), name='contact-submissions'),
    path('contact/submissions/read/<int:pk>/', mark_submission_read, name='contact-read'),
    path('contact/submissions/delete/<int:pk>/', ContactSubmissionDeleteView.as_view(), name='contact-delete'),
    path('packages/', PackageListView.as_view(), name='package-list'),
    path('packages/add/', PackageCreateView.as_view(), name='package-create'),
    path('packages/edit/<int:pk>/', PackageUpdateView.as_view(), name='package-update'),
    path('packages/delete/<int:pk>/', PackageDeleteView.as_view(), name='package-delete'),
    path('insurance/', InsuranceListView.as_view(), name='insurance-list'),
    path('insurance/add/', InsuranceCreateView.as_view(), name='insurance-create'),
    path('insurance/edit/<int:pk>/', InsuranceUpdateView.as_view(), name='insurance-update'),
    path('insurance/delete/<int:pk>/', InsuranceDeleteView.as_view(), name='insurance-delete'),
    path('legal/', LegalPageListView.as_view(), name='legal-list'),
    path('legal/add/', LegalPageCreateView.as_view(), name='legal-create'),
    path('legal/edit/<int:pk>/', LegalPageUpdateView.as_view(), name='legal-update'),
    path('legal/delete/<int:pk>/', LegalPageDeleteView.as_view(), name='legal-delete'),
    path('settings/', global_settings_manage, name='global-settings'),
    path('social/', SocialLinkListView.as_view(), name='social-list'),
    path('social/add/', SocialLinkCreateView.as_view(), name='social-create'),
    path('social/edit/<int:pk>/', SocialLinkUpdateView.as_view(), name='social-update'),
    path('social/delete/<int:pk>/', SocialLinkDeleteView.as_view(), name='social-delete'),
    path('menu/', MenuGroupListView.as_view(), name='menu-list'),
    path('menu/add/', MenuGroupCreateView.as_view(), name='menu-create'),
    path('menu/edit/<int:pk>/', MenuGroupUpdateView.as_view(), name='menu-update'),
    path('menu/delete/<int:pk>/', MenuGroupDeleteView.as_view(), name='menu-delete'),
    path('schedule/create/', DoctorScheduleCreateView.as_view(), name='schedule-create'),
    path('load-doctors/', load_doctors_by_specialization, name='load_doctors_admin'),
    path('schedule/', DoctorScheduleListView.as_view(), name='schedule_list'),
    path('schedule/<int:pk>/update/', DoctorScheduleUpdateView.as_view(), name='schedule_update'),
    path('schedule/<int:pk>/delete/', DoctorScheduleDeleteView.as_view(), name='schedule_delete'),
    path('leave/create/', DoctorLeaveCreateView.as_view(), name='leave_create'),
    path('leave/', DoctorLeaveListView.as_view(), name='leave_list'),
    path('leave/<int:pk>/update/', DoctorLeaveUpdateView.as_view(), name='leave_update'),
    path('leave/<int:pk>/delete/', DoctorLeaveDeleteView.as_view(), name='leave_delete'),
    path('bookings/', booking_list, name='booking_list'),
    path('bookings/<int:pk>/status/', update_booking_status, name='update_booking_status'),
   path('bookings/<int:pk>/delete/', delete_booking, name='delete_booking'),
    path('gallery/', GalleryListView.as_view(), name='gallery_list'),
    path('gallery/add/', GalleryCreateView.as_view(), name='gallery_add'),
    path('gallery/<int:pk>/edit/', GalleryUpdateView.as_view(), name='gallery_edit'),
    path('gallery/<int:pk>/delete/', GalleryDeleteView.as_view(), name='gallery_delete'),
    path('gallery/image/<int:pk>/delete/', gallery_image_delete, name='gallery_image_delete'),
]
    

   
    

